<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>3c2035b6-8e74-4a86-81ab-1490dad4de87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24_PpKHqu9k5xvC_PKBDde05PITb4YR-YeUVmLF2zG0MTYjpYY19V-jozE0oAUgDZusphWV9R7zccQc8xeHzZgszdEW8ukagjXT0j7N2P1wItPHct46hMQyVRQH6ltQx7wCfgy9layzY0J-dk0WfKIxxJwXmOg5zecCGrgw9TBcuYMpPBiRUsL28xRTOIWT5_xm2vgXaAc4QKnVRp6jJk8H8P3uzGJW5TfrZ4BJ9F-ggJR-678&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=7d8bcc0b2146c39b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RegistroUser/iframe_html1body1div5div2iframe1_c-xqrgznx5hi47</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24_PpKHqu9k5xvC_PKBDde05PITb4YR-YeUVmLF2zG0MTYjpYY19V-jozE0oAUgDZusphWV9R7zccQc8xeHzZgszdEW8ukagjXT0j7N2P1wItPHct46hMQyVRQH6ltQx7wCfgy9layzY0J-dk0WfKIxxJwXmOg5zecCGrgw9TBcuYMpPBiRUsL28xRTOIWT5_xm2vgXaAc4QKnVRp6jJk8H8P3uzGJW5TfrZ4BJ9F-ggJR-678&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=7d8bcc0b2146c39b')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
