<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>995f6269-a2b2-46ed-846b-79b838da0902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27ICE3K9bTYTlvtJEN-5tZToaHNwD_7yj41WDQ2ey3d3cyrYZ0ifqJWbOuJJygMWH9SDiFe-3WOT4a8OXlrFp-E9tif-j_bukgQyV1TSULxHMYM_lFw7Gy1fWoMl4_dzT7z0BTpboZrEZ4YK082upZl3LiknlVndN7qVmjixmyI-FC03UnA-asYXWFUCObZ8UoQ45TVYfOd2JD6CzqNYSHJCU0PISEe4yKO32GaF4i2OIX1FDA&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=b36c03c05590554</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RegistroUser/iframe_html1body1div5div2iframe1_c-xqrgznx5hi47</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27ICE3K9bTYTlvtJEN-5tZToaHNwD_7yj41WDQ2ey3d3cyrYZ0ifqJWbOuJJygMWH9SDiFe-3WOT4a8OXlrFp-E9tif-j_bukgQyV1TSULxHMYM_lFw7Gy1fWoMl4_dzT7z0BTpboZrEZ4YK082upZl3LiknlVndN7qVmjixmyI-FC03UnA-asYXWFUCObZ8UoQ45TVYfOd2JD6CzqNYSHJCU0PISEe4yKO32GaF4i2OIX1FDA&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=b36c03c05590554')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
