<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>e432be59-157b-40ad-8439-2535345cf4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26Zm0DbUYsAzfniqKf--THWAmP_msRHiHFO1w14vDUMgPSgRbp8n621HkCa2NLCJDPyu0nysF7w00RhoaxB9F3HBI3hGlZIWYNnJOwdZQ06X5Gy5UDakubeZj5SXCkjwRwNrn74ZlDr3HzzrBgrpuZFB0MIk_O6GxMqshj248kUlPYNRHHF6jYKday77LA-Y7ScCLlfbEnvIEntI2SoJiRk-AmDAkccULxJvmGlDPIEIiV1xAg&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=7397f5069af1f8a1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RegistroUser/iframe_html1body1div5div2iframe1_c-xqrgznx5hi47</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26Zm0DbUYsAzfniqKf--THWAmP_msRHiHFO1w14vDUMgPSgRbp8n621HkCa2NLCJDPyu0nysF7w00RhoaxB9F3HBI3hGlZIWYNnJOwdZQ06X5Gy5UDakubeZj5SXCkjwRwNrn74ZlDr3HzzrBgrpuZFB0MIk_O6GxMqshj248kUlPYNRHHF6jYKday77LA-Y7ScCLlfbEnvIEntI2SoJiRk-AmDAkccULxJvmGlDPIEIiV1xAg&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=7397f5069af1f8a1')])[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
