<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>df333a0d-e667-4e10-a5c8-4025cf4790a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq25v3JA3V5XyA67zmxMtmo9dCR15OLMuk-8mIROl2IcQReE5S4jc9kQjtkHqRIrG4CTKQIiDOHOpb-9xScyQRMp7WZOyW5sGQz2eSL8JTEeuMNJIMGI2PBVNEM7rd19C2QzUowweLsPRxs4qnY_6mS9LBB4TFoZQXcmYq0JzQsi32XOAkg_DAdK-6LVAWNT663k12boGB6CCNc_0oudLZAnxvoKZGt1mc2PcY_-85cymHqtFkaw&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=5d8c53cb7f18d00d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RegistroUser/iframe_html1body1div5div2iframe1_c-xqrgznx5hi47</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25v3JA3V5XyA67zmxMtmo9dCR15OLMuk-8mIROl2IcQReE5S4jc9kQjtkHqRIrG4CTKQIiDOHOpb-9xScyQRMp7WZOyW5sGQz2eSL8JTEeuMNJIMGI2PBVNEM7rd19C2QzUowweLsPRxs4qnY_6mS9LBB4TFoZQXcmYq0JzQsi32XOAkg_DAdK-6LVAWNT663k12boGB6CCNc_0oudLZAnxvoKZGt1mc2PcY_-85cymHqtFkaw&amp;k=6Lc3i14UAAAAAHVkSmSnecXg9DpfrJ1gYeuOzaCw&amp;id=5d8c53cb7f18d00d')])[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
