<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_uTest</name>
   <tag></tag>
   <elementGuidId>5bbc02eb-6ee5-4f50-ad38-786fe44c4d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark.signup-consent__checkbox.error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='regs_container']/div/div[2]/div/div[2]/div/form/div[5]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark signup-consent__checkbox error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{error: userForm.termOfUse.$error.required}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regs_container&quot;)/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;sign-up-form-container&quot;]/div[@class=&quot;ui-view&quot;]/div[1]/form[@class=&quot;form-group-box user-form ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse ng-valid-ok-password ng-valid-minlength ng-valid-validation-match&quot;]/div[@class=&quot;row col-xs-12&quot;]/label[@class=&quot;input-check-box signup-consent&quot;]/span[@class=&quot;checkmark signup-consent__checkbox error&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='regs_container']/div/div[2]/div/div[2]/div/form/div[5]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/span</value>
   </webElementXpaths>
</WebElementEntity>
